---
title: "Abby"
author: "Abby"
date: "11/5/2021"
output: html_document
---

```{r}
R.version
```

```{r}
library(ape)
library(fastmatch)
library(quadprog)
library(phangorn)
library(phytools)
library(geiger)
```

```{r}
mol.tree<-read.nexus(file="NJst.tre")
mol.tree
nodelabels(text=1:mol.tree$Nnode,node=1:mol.tree$Nnode+Ntip(mol.tree))
```

```{r}
mol.tree<-read.nexus(file="NJst.tre")
plot(mol.tree,no.margin=TRUE,edge.width=2)
nodelabels(text=1:mol.tree$Nnode,node=1:mol.tree$Nnode+Ntip(mol.tree))


plot(mol.tree, "fan", main="Molecular Tree", edge.width = 3, edge.color = "pink", show.tip.label = FALSE)
arc.cladelabels(tree=mol.tree, "Serpa Clade", node = 55, ln.offset=1.02,
   lab.offset=1.06, cex=1, orientation="curved")
```

```{r}
##all the species names 
mol.tree$tip.label
```

```{r}
library('stringr') 
species <- mol.tree$tip.label
string <- paste(species, collapse= "")
string
str_split(species,",", simplify= TRUE)

```

```{r}
text.string<-
    "((((humpback wahle, fin whale), (Antarctic minke whale, common minke whale)), bowhead whale), sperm whale);"
```

```{r}
string <- "((A. alala negra, A. corcyra aretina, A. tracta, A. pithys, A. donysa donysa), ((A. serpacelerio, A. seriphiaaquillia, A. seriphiatherasia), (A. melonaleucocoma, A. salmoneus colada, A. cythereacytherea, A. cythereadaguana, A. epioneagilla, A. etheldaethelda, A. thessaliathessalia, A. iphicleolathessalita, A. iphiclusiphiclus, A. shuara, A. plesaurephliassa, A. basiloides, A. atticaattica, A. leucerioides, A. saundersiisaundersii, A. boreasboreas, A. rothschildi, A. sichaeus, A. cocalacocala, A. leucophthalmairminella, A. irminatumida, A. pollina, A. lycoriaslara, A. lycoriasspruceana, A. erotia erotia, A. mesentina, A. phylaca pseudaethalia, A. capucinus capucinus, A. heraclea heraclea, A. naxia naxia, A. justina valentina, A. olynthia, A. jordani, A. zinazina, A. zinairma, A. delinita delinita, A. boeotia boeotia, A. maleaaethalia)));"

morph.tree<-read.tree(text=string)
plot(morph.tree,no.margin=TRUE,edge.width=2)
nodelabels(text=1:morph.tree$Nnode,node=1:morph.tree$Nnode+Ntip(morph.tree))

plot(morph.tree, "fan", main="Morphological Tree", edge.width = 3, edge.color = "pink", show.tip.label = FALSE)
arc.cladelabels(tree=morph.tree, "Serpa Clade", node = 3, ln.offset=1.02,
   lab.offset=1.06, cex=1, orientation="curved")
```
```{r}
#Morphological tree plot
p <- ggtree(morph.tree, color="purple", size=0.5, linetype="dotted")
p <- p + geom_tiplab(size=2)
p <- p + geom_cladelabel(node = 3, label="Serpa Clade", align=TRUE, offset=1, angle=90) 
p
```

```{r}
#Molecular tree plot 
g <- ggtree(mol.tree, color="green", size=0.5, linetype="dotted")
g <- g + geom_tiplab() 
g <- g + geom_cladelabel(node=47, label="Serpa", angle = 90, 
                  color="red2", align=TRUE) 
g <- g + geom_hilight(node=6, fill="gold")
g
```



```{r}
library("gridExtra")
grid.arrange(ggtree(tree) + ggtitle("(Phylogram) rectangular layout"),
             ggtree(tree, branch.length='none') + ggtitle("(Cladogram) rectangular layout"),
         ggtree(tree, layout="slanted") + ggtitle("(Phylogram) slanted layout"),
             ggtree(tree, layout="slanted", branch.length='none') + ggtitle("(Cladogram) slanted layout"),
         ggtree(tree, layout="circular") + ggtitle("(Phylogram) circular layout"),
             ggtree(tree, layout="circular", branch.length="none") + ggtitle("(Cladogram) circular layout"),
         ggtree(tree, layout="unrooted") + ggtitle("unrooted layout"),
         ncol=2)
```
