---
title: "Marta"
author: "Marta"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

understanding packages

```{r packages}
install.packages("expm")
install.packages("gee")
install.packages("igraph")
install.packages("ape")
install.packages("fastmatch")
install.packages("quadprog")
install.packages("phangorn")
install.packages("phytools")
install.packages("geiger")
```

```{r}
library(ape)
library(fastmatch)
library(quadprog)
library(phangorn)
library(phytools)
library(geiger)
```

```{r nex}
nex.tree<-read.nexus.data(file="matrix_from_app2_xl_file.nex")
nexus2DNAbin(nex.tree)
plot.phylo(nex.tree)
```
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ok i'm sleeping now but i think the answer is converting this xl file to readable tre
```{r}
as.phylo.formula(~Order/Family/Genus/Species, data =  (file="matrix_from_app2_xl_file.nex"))
```

```{r}
nex2.tree<-read.newick("matrix_from_app2_xl_file.nex")
plotTree(nex2.tree)
```

```{r}
install.packages("TreeTools")
library(TreeTools)
```
```{r}
as_phydat <- ReadAsPhyDat("matrix_from_app2_xl_file.nex")
as_phydat
summary(as_phydat)
raw_data <- ReadCharacters("matrix_from_app2_xl_file.nex")
my_data <- MatrixToPhyDat(raw_data)#i think these are important
```

```{r}
read.nexus.data("matrix_from_app2_xl_file.nex")
```
